#!/usr/bin/env python3
# Copyright (c) 2026-present The Bitcoin Core developers
# Distributed under the MIT software license, see the accompanying
# file COPYING or http://www.opensource.org/licenses/mit-license.php.
"""Convert BIP54 sigop JSON vectors into bip54_sigops fuzz inputs."""

import argparse
import hashlib
import json
from pathlib import Path
import sys


SOURCE_DIR = Path(__file__).resolve().parents[2]
FUNCTIONAL_TEST_DIR = str(SOURCE_DIR / "test" / "functional")
if FUNCTIONAL_TEST_DIR not in sys.path:
    sys.path.insert(0, FUNCTIONAL_TEST_DIR)

from test_framework.messages import CTransaction, CTxOut, from_hex, ser_string  # noqa: E402


def vector_to_fuzz_input(vector):
    tx = from_hex(CTransaction(), vector["tx"])
    spent_outputs = [from_hex(CTxOut(), txo) for txo in vector["spent_outputs"]]
    if len(tx.vin) != len(spent_outputs):
        raise ValueError(
            f"transaction has {len(tx.vin)} inputs but vector has "
            f"{len(spent_outputs)} spent outputs"
        )
    if len(tx.vin) > 0xffff:
        raise ValueError("fuzz input format cannot encode more than 65535 inputs")

    fuzz_input = len(tx.vin).to_bytes(2, "little")
    for txin, spent_output in zip(tx.vin, spent_outputs):
        fuzz_input += ser_string(txin.scriptSig)
        fuzz_input += ser_string(spent_output.scriptPubKey)
    return fuzz_input


def main():
    parser = argparse.ArgumentParser(
        description=(
            "Convert bip54_sigops.json generated by bip54_tests into a seed "
            "corpus for the bip54_sigops fuzz target."
        )
    )
    parser.add_argument("vectors", type=Path, help="BIP54 sigop JSON vector file")
    parser.add_argument("output_dir", type=Path, help="destination corpus directory")
    args = parser.parse_args()

    with args.vectors.open(encoding="utf8") as vectors_file:
        vectors = json.load(vectors_file)
    if not isinstance(vectors, list):
        raise ValueError("top-level JSON value must be an array")

    args.output_dir.mkdir(parents=True, exist_ok=True)
    generated = set()
    for index, vector in enumerate(vectors):
        try:
            fuzz_input = vector_to_fuzz_input(vector)
        except (KeyError, TypeError, ValueError) as e:
            raise ValueError(f"vector {index}: {e}") from e
        digest = hashlib.sha256(fuzz_input).hexdigest()
        (args.output_dir / digest).write_bytes(fuzz_input)
        generated.add(digest)

    print(f"Wrote {len(generated)} unique seeds from {len(vectors)} vectors")


if __name__ == "__main__":
    main()
