name: CI

on:
  pull_request:
  push:
    branches: ['**']
    tags-ignore: ['**']

permissions:
  contents: read

concurrency:
  group: ${{ github.event_name != 'pull_request' && github.run_id || github.ref }}
  cancel-in-progress: true

env:
  CI_FAILFAST_TEST_LEAVE_DANGLING: 1
  CIRRUS_CACHE_HOST: http://127.0.0.1:12321/
  REPO_USE_CIRRUS_RUNNERS: 'bitcoin/bitcoin'

defaults:
  run:
    shell: bash

jobs:
  freebsd:
    name: 'FreeBSD 14, system_tests only'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: ${{ vars.SKIP_BRANCH_PUSH != 'true' || github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v5
      - uses: cross-platform-actions/action@v0.29.0
        with:
          operating_system: freebsd
          version: '14.2'
          architecture: x86_64
          shell: bash
          memory: 4G
          cpu_count: 2
          run: |
            sudo env IGNORE_OSVERSION=yes pkg update -f
            sudo env IGNORE_OSVERSION=yes pkg install -y \
              cmake ninja pkgconf \
              boost-libs libevent sqlite3 \
              libzmq4 python311 py311-sqlite3 py311-pyzmq \
              capnproto \
              git bash

            cmake -B build -G Ninja \
              -DCMAKE_BUILD_TYPE=Release \
              -DBUILD_TESTS=ON -DBUILD_GUI=OFF -DBUILD_BENCH=OFF \
              -DENABLE_WALLET=ON -DWITH_SQLITE=ON -DWITH_BDB=OFF \
              -DWITH_MINIUPNPC=OFF -DWITH_NATPMP=OFF -DWITH_QRENCODE=OFF \
              -DWITH_ZMQ=ON -DENABLE_IPC=ON -DREDUCE_EXPORTS=ON -DWERROR=ON

            cmake --build build --target test_bitcoin -j2 || (
              cmake --build build --target test_bitcoin -j1 --verbose
              exit 1
            )
            [ -x ./build/bin/test_bitcoin ] || (find build -name test_bitcoin -type f; exit 1)

            set -o pipefail
            ./build/bin/test_bitcoin --run_test=system_tests --log_level=all | tee freebsd.system_tests.log
            rc=$?
            exit $rc

  netbsd:
    name: 'NetBSD 10, system_tests only'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: ${{ vars.SKIP_BRANCH_PUSH != 'true' || github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v5
      - uses: cross-platform-actions/action@v0.29.0
        with:
          operating_system: netbsd
          version: '10.0'
          architecture: x86_64
          shell: bash
          memory: 4G
          cpu_count: 2
          run: |
            set -euo pipefail
            export PATH="/usr/pkg/sbin:/usr/pkg/bin:$PATH"

            if ! command -v pkgin >/dev/null 2>&1; then
              export PKG_PATH="https://cdn.netbsd.org/pub/pkgsrc/packages/NetBSD/amd64/10.0_2025Q2/All/"
              sudo env PKG_PATH="$PKG_PATH" /usr/sbin/pkg_add -v pkgin
            fi

            sudo pkgin -y update
            sudo pkgin -y install \
              cmake ninja-build pkgconf \
              boost libevent sqlite3 zeromq \
              python311 py311-zmq \
              capnproto \
              clang libcxx \
              bash || true
            command -v git >/dev/null 2>&1 || sudo pkgin -y install git git-base || sudo pkgin -y install git-base

            export CC="clang"
            export CXX="clang++"

            cmake -B build -G Ninja \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_PREFIX_PATH="/usr/pkg" \
              -DCMAKE_C_COMPILER=/usr/pkg/bin/clang \
              -DCMAKE_CXX_COMPILER=/usr/pkg/bin/clang++ \
              -DCMAKE_CXX_FLAGS="-stdlib=libc++" \
              -DCMAKE_EXE_LINKER_FLAGS="-stdlib=libc++" \
              -DBUILD_TESTS=ON -DBUILD_GUI=OFF -DBUILD_BENCH=OFF \
              -DENABLE_WALLET=ON -DWITH_SQLITE=ON -DWITH_BDB=OFF \
              -DWITH_MINIUPNPC=OFF -DWITH_NATPMP=OFF -DWITH_QRENCODE=OFF \
              -DWITH_ZMQ=ON -DENABLE_IPC=ON -DREDUCE_EXPORTS=ON -DWERROR=ON

            cmake --build build --target test_bitcoin -j2
            ./build/bin/test_bitcoin --run_test=system_tests --log_level=all | tee netbsd.system_tests.log
            rc=$?
            exit $rc

  openbsd:
    name: 'OpenBSD 7.7, system_tests only'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: ${{ vars.SKIP_BRANCH_PUSH != 'true' || github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v5
      - uses: cross-platform-actions/action@v0.29.0
        with:
          operating_system: openbsd
          version: '7.7'
          architecture: x86_64
          shell: sh
          memory: 4G
          cpu_count: 2
          run: |
            ulimit -d 2097152
            ulimit -s 8192
            echo 'https://cdn.openbsd.org/pub/OpenBSD' | sudo tee /etc/installurl >/dev/null
            export PKG_PATH="https://cdn.openbsd.org/pub/OpenBSD/7.7/packages/amd64/"
            sudo pkg_add -U \
              cmake ninja \
              boost libevent sqlite3 \
              zeromq python%3.11 py3-zmq \
              git bash

            sudo ln -sf /usr/local/bin/python3.11 /usr/local/bin/python3 || true

            cmake -B build -G Ninja \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_C_COMPILER=/usr/bin/cc \
              -DCMAKE_CXX_COMPILER=/usr/bin/c++ \
              -DBUILD_TESTS=ON -DBUILD_GUI=OFF -DBUILD_BENCH=OFF \
              -DENABLE_WALLET=ON -DWITH_SQLITE=ON -DWITH_BDB=OFF \
              -DWITH_MINIUPNPC=OFF -DWITH_NATPMP=OFF -DWITH_QRENCODE=OFF \
              -DWITH_ZMQ=ON -DENABLE_IPC=OFF -DREDUCE_EXPORTS=ON -DWERROR=ON

            cmake --build build --target test_bitcoin -j2
            ./build/bin/test_bitcoin --run_test=system_tests --log_level=all | tee openbsd.system_tests.log
            rc=$?
            exit $rc
